# Site settings

title: Naminz Research
header-img: img/home-bg.jpg
email: njeong3@mail.gatech.edu
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/NaminResearch"
url: "http://Naminz.github.io"
github_username:  Naminz
project_repository: NaminResearch
disqus_shortname: project-pages

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
